### ISSUE TITLE
Crash when loading heist

### ISSUE THREAD

**Issue by bergdavi** [Pd2VoidTeam/VoidUI#11]
Application has crashed: C++ exception
[string "lib/managers/musicmanager.lua"]:195: attempt to concatenate field 'current_track' (a nil value)

SCRIPT STACK

recreate_right() lib/managers/hud/newhudstatsscreen.lua:250
init() lib/managers/hud/newhudstatsscreen.lua:82
new() core/lib/utils/coreclass.lua:35
_setup_stats_screen() lib/managers/hudmanagerpd2.lua:1044
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
show_stats_screen() lib/managers/hudmanagerpd2.lua:1054
_setup_player_info_hud_pd2() @mods/VoidUI/lua/HudManager.lua:224
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
init_finalize() lib/managers/hudmanager.lua:169
init_finalize() lib/setups/gamesetup.lua:622
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.79.387.
	CPU : Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     16244MB 932KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Fanged-Hex** [comment]
The log seems to be about a problem with the music.

Could we have your mods list ? You have only our mod or there is other mods ?

**Comment by bergdavi** [comment]
I have several other mods, but none of them do anything with the music as far as i know (except for beardlib maybe).

My mods:
Adva Asault Info Wolfhud Standalone
akimboalternate
Auto-Cardpicker
BeardLib
BuyAllAssets
DelayedCallsFix
Difficulty Screen Animation
Disconnect a player
Drag and Drop Inventory
Enhanced Hitmarkers
More Weapon Stats
No Contract Broker Images
Hudlist + Game info manager
Press2hold
ReLUA
Slide and Bolt Catch
Stop the crimespree loss on crash

**Comment by bergdavi** [comment]
I've also tried disabling all my mods except  for void ui and the game still crashes.

**Comment by Fanged-Hex** [comment]
Okay, I will check with other devs if the bug has been found and fixed or not.
I think Overkill modified something and it makes our mod crash :(

I will update this issue when we found stuff about it !

**Comment by Xeletron** [comment]
Crimefest Day 3 broke the stats screen, download the 1.1.1 version from here then disable the stats screen.

**Comment by bergdavi** [comment]
That fixed the crash, thanks
