### ISSUE TITLE
Crashing when quitting to lobby

### ISSUE THREAD

**Issue by w4term4n12** [Pd2VoidTeam/VoidUI#12]
when I'm in a heist and I click quit to the main menu it crashes my game.

**Comment by Fanged-Hex** [comment]
Two things : 
1) We need to crashlog to be able to help you and maybe fix the error(s) : Use this guide https://steamcommunity.com/sharedfiles/filedetails/?id=587236764 to find where the crashlog is and post it as an answer here :)
2) We are still in CrimeFest so as payday 2 mod developers, we try to fix as fast as we can the bugs introduced in the last CrimeFest day update, you can try to use the dev branch : https://github.com/Pd2VoidTeam/VoidUI/archive/Development.zip but 0 garanteed that the bug is fixed so if it's still there, just post your crashlog as the 1) suggest :)

**Comment by w4term4n12** [comment]
@Fanged-Hex

Sat Oct 28 15:25:13 2017


Application has crashed: C++ exception
[string "lib/managers/hud/hudteammate.lua"]:1827: attempt to index a nil value



SCRIPT STACK

set_absorb_active() lib/managers/hudmanagerpd2.lua:472
set_damage_absorption() lib/managers/playermanager.lua:256
sync_hostage_headcount() lib/managers/group_ai_states/groupaistatebase.lua:3783
update() @mods/VoidUI-Development/lua/HudAssaultCorner.lua:1555
update() lib/managers/group_ai_states/groupaistatebesiege.lua:44
update() lib/managers/groupaimanager.lua:15
update() lib/setups/gamesetup.lua:660
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

**Comment by OmicronPerseiEight** [comment]
Hi, I also have crashed under similar conditions and with a similar crashlog.  I've created a thread about it on the Steam Group http://steamcommunity.com/groups/VoidUI/discussions/0/1480982338951306204/.  I would copy it over, but it's several posts and seemed like it would take up a large amount of real estate, so I linked it instead.

Highlights: seems related to damage absorption, possibly from the Forced Friendship aced skill.  Issue persists in Development branch (for me), and I was using the one that was 36 commits ahead of master, not 37 like are available now.

Thanks for your work!  This HUD is really great, and I think it's rare to find a mod that has such a pleasant combination of functionality and aesthetics (even despite a bit of totally expected and reasonable instability during an update-fest).

**Comment by w4term4n12** [comment]
@Fanged-Hex oh and I forgot to say that I'm using the dev version of the hud if that helps.

**Comment by Fanged-Hex** [comment]
Do you have any mods with it ? Or is it the only one mod you have installed ?

**Comment by w4term4n12** [comment]
@Fanged-Hex Only Voidui

**Comment by Fanged-Hex** [comment]
@Xeletron & me will look into this bug if we find anything to fix it !

**Comment by Fanged-Hex** [comment]
So with @Xeletron's help, we fixed the bug for our side we still needs confirmation that the bug is entirely fixed :)

**Comment by OmicronPerseiEight** [comment]
Awesome, thank you!

**Comment by LT71** [comment]
After some testing the result is:
Berfore the update there was a crash 5 times of 20 tries

After upgrading to the latest dev version the result was 0 out of 55 so it seems its fixed. Cant say for sure tho.

**Comment by Fanged-Hex** [comment]
The bug was about Overkill using a network function inside an hud function without checking if the network was there, so when you leave, if the function is called at the same time, the game doesn't find the network and crash :(
