### ISSUE TITLE
[Development Build] Scoreboard Doesn't Show

### ISSUE THREAD

**Issue by NerdVenom** [Pd2VoidTeam/VoidUI#14]
When using the dev build with the scoreboard enabled, pressing TAB does nothing. The Scoreboard doesn't show up at all. Is this intended right now, a mod conflict or a bug?

Only other HUD mods I'm using would be : Lobby Player Info, GameInfoManager and HUDList.

**Comment by Fanged-Hex** [comment]
Maybe one of it is overwritting our stuff, on my side (I'm using the dev) and it works as intended. Everything else is working fine ?

**Comment by NerdVenom** [comment]
Everything but the Scoreboard. I'll try disabling my other mods when I can and see if that fixes it.

**Comment by NerdVenom** [comment]
OK, fixed this by deleting the "VoidUI.txt" in Payday 2/Mods/saves. Must have been some previous setting I had that messed it up.
