### ISSUE TITLE
[CRASH] When dominating cops

### ISSUE THREAD

**Issue by ATTAFWRD** [Pd2VoidTeam/VoidUI#17]
- [ *] I am running the latest version
- [ *] I made sure this issue doesn't persist without this mod
- [ *] I checked to make sure that this issue has not already been filed

Mods used are:

- VoidUI
- Simple Toggle Interaction
- BuyAllAssets
- NGBTO
- Enhanced-FastNet
- Lobby Player Info
- Skip and Auto-Select

Application has crashed: C++ exception
mods/Void UI/lua/jokers.lua:53: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

**Comment by ATTAFWRD** [comment]
[CRASH AGAIN] When pressing TAB after a player joined (not hosting)

Application has crashed: C++ exception
mods/Void UI/lua/HudScoreboard.lua:1537: bad argument #16 to 'format' (number expected, got nil)

SCRIPT STACK

set_player() @mods/Void UI/lua/HudScoreboard.lua:1537
add_scoreboard_panel() @mods/Void UI/lua/HudScoreboard.lua:1026
add_teammate_panel() @mods/Void UI/lua/HudManager.lua:517
add_mugshot() lib/managers/hudmanager.lua:1046
add_mugshot_by_unit() lib/managers/hudmanager.lua:1014
add_character() lib/managers/criminalsmanager.lua:289
set_unit() lib/network/base/networkpeer.lua:2263
lib/network/handlers/unitnetworkhandler.lua:48


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

**Comment by Fanged-Hex** [comment]
Thank you for your issue, we will look into that problem and try to fix it :)

**Comment by Xeletron** [comment]
I pushed an update to the dev branch that should hopefully fix these, need confirmation

**Comment by ATTAFWRD** [comment]
Seems fine with using Dev branch.
