### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by LudwigVonWolfgang** [Pd2VoidTeam/VoidUI#19]
**Hi, I have seen this error alot in my log:** 

FATAL ERROR:  (..\src\InitiateState.cpp:409) mods/Void UI/Main.lua:69: attempt to index global 'MenuManager' (a nil value)
stack traceback:
	mods/Void UI/Main.lua:69: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:120: in function 'RunHookFile'
	mods/base/base.lua:113: in function 'RunHookTable'
	mods/base/base.lua:142: in function 'require'
	[string "core/lib/system/coremodule.lua"]:52: in function 'import'
	[string "core/lib/managers/subtitle/coresubtitlemanage..."]:5: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "core/lib/system/coremodule.lua"]:52: in function 'import'
	[string "core/lib/setups/coresetup.lua"]:15: in main chunk
	...
	[string "lib/setups/setup.lua"]:21: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "lib/setups/menusetup.lua"]:1: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "lib/entry.lua"]:13: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk

**If I were to fix the error I would just remove:**
function MenuManager:toggle_chatinput()
	if Application:editor() then
		return
	end
	if SystemInfo:platform() ~= Idstring("WIN32") then
		return
	end
	if self:active_menu() then
		return
	end
	if not managers.network:session() then
		return
	end
	if managers.hud then
		managers.hud:toggle_chatinput()
		return true
	end
end

**Then add it back at the bottom like this:** 
if RequiredScript == "lib/managers/menumanager" then
function MenuManager:toggle_chatinput()
	if Application:editor() then
		return
	end
	if SystemInfo:platform() ~= Idstring("WIN32") then
		return
	end
	if self:active_menu() then
		return
	end
	if not managers.network:session() then
		return
	end
	if managers.hud then
		managers.hud:toggle_chatinput()
		return true
	end
end
end

**Comment by Xeletron** [comment]
Oh yeah, I remember that error. It doesn't crash the game or anything so I didn't really care about it, but if its annoying then sure, I'll fix it.
