### ISSUE TITLE
[CRASH] Game crash when starting a heist with this and WolfHUD simultaneously

### ISSUE THREAD

**Issue by BreakinBenny** [Pd2VoidTeam/VoidUI#21]
VoidUI is quite the eye candy because of how it's more responsive and friendly compared to the vanilla HUD and whatnot, but using it with WolfHUD crashes the game.

Is it possible to do like Luffyyy did with HoloUI, by disabling certain stuff WolfHUD requires to display its own HUD and place VoidUI on top?

**Comment by Xeletron** [comment]
I guess I could see into that. for now you can use HUDList mod, thats basicly what wolfhud uses for timers and stuff and it works with VoidUI

**Comment by BreakinBenny** [comment]
Now let's see…, the crashlog mentions the following: `
Wed Nov 22 21:45:38 2017


Application has crashed: C++ exception
mods/Holo/Hooks/HUD/HUDHooks.lua:33: attempt to index field '_bg_box' (a nil value)



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
_create_present_panel() lib/managers/hudmanagerpd2.lua:911
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:643
_setup_player_info_hud_pd2_original() @mods/WolfHUD-master/lua/HUDList.lua:113
setup_player_info_hud_pd2() @mods/WolfHUD-master/lua/DrivingHUD.lua:938
original() @mods/Void UI/lua/HudManager.lua:224
original() @mods/base/req/core/Hooks.lua:185
_setup_player_info_hud_pd2() @mods/base/req/core/Hooks.lua:260
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
init_finalize() lib/managers/hudmanager.lua:169
original() lib/setups/gamesetup.lua:621
init_finalize() @mods/base/req/core/Hooks.lua:260
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422`

**Comment by Xeletron** [comment]
That crash seems to be caused by HoloUI, both mods edit the same files. try disabling the hud portion of holo

**Comment by ATTAFWRD** [comment]
Just use **VoidUI** without other Info HUD. If you want the timer and stuffs, use HUDList with VoidUI. That's what I'm using and this is the best. Of course you need to download the accessory mods if you're already used to have them..

**inb4 what mods I'm using now (and the only you need):**

- VoidUI **(OBVIOUSLY)**
- HUDList (with GameInfoManager)
- Lobby Player Info
- Enhanced-Fast.Net
- Buy All Assets
- Simple Toggle Interaction
- Faster Skip
- Skip and Auto-Select
- Force Ready
- TranslucentMissionBriefingGUI
- Steam Profile Redirection
- SteamInventoryInLobby
- Newbies go back to overkill

**Comment by BreakinBenny** [comment]
Good, but I'll leave out the Buy All Assets.

**Comment by BreakinBenny** [comment]
@Xeletron and @ATTAFWRD I think I know a compromise; how about inserting code into WolfHUD that tells it to disable many of *its* conflicting HUD alterations?

**Comment by BreakinBenny** [comment]
Here's my crashlog from using Void UI plus WolfHUD, should've thought about it before I posted the one with HoloUI…

----------------------------------------------------------------------

Tue Jan 23 14:14:20 2018


Application has crashed: C++ exception
mods/Void UI/lua/HudTemp.lua:73: attempt to perform arithmetic on field '_bg_h' (a nil value)



SCRIPT STACK

init_original() @mods/Void UI/lua/HudTemp.lua:68
init() @mods/WolfHUD-master/lua/CustomHUD.lua:4575
new() core/lib/utils/coreclass.lua:35
_create_temp_hud() lib/managers/hudmanagerpd2.lua:1232
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:651
_setup_player_info_hud_pd2_original() @mods/WolfHUD-master/lua/HUDList.lua:113
setup_player_info_hud_pd2() @mods/WolfHUD-master/lua/DrivingHUD.lua:938
_setup_player_info_hud_pd2() @mods/Void UI/lua/HudManager.lua:224
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
original() lib/setups/gamesetup.lua:663
init_finalize() @mods/base/req/core/Hooks.lua:260
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.86.509.
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[23.21.13.9065]
	Language : english
	Memory :     8132MB 48KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Högtalare (High Definition Audio Device))

**Comment by Xeletron** [comment]
You have to disable a lot of things in WolfHud if you want it to work, like the custom hud, tab screen and so on. it might still not work even after disabling that
