### ISSUE TITLE
[CRASH] When dominate (DEV)

### ISSUE THREAD

**Issue by ATTAFWRD** [Pd2VoidTeam/VoidUI#23]
**Crashed (again) when someone dominate a cop.**
Using dev branch.

Application has crashed: C++ exception
mods/Void UI/lua/jokers.lua:79: attempt to index local 'unit' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

**Comment by Xeletron** [comment]
hmm, I see what causes the crash, but its related to trading a joker in and not dominating a cop. Should be fixed in the next update though
