### ISSUE TITLE
CTD in Blackscreen when heist start

### ISSUE THREAD

**Issue by ATTAFWRD** [Pd2VoidTeam/VoidUI#33]
Application has crashed: C++ exception
mods/Void UI/lua/HudBlackscreen.lua:95: attempt to compare number with nil

SCRIPT STACK

set_job_data() lib/managers/hud/hudblackscreen.lua:98
set_blackscreen_job_data() lib/managers/hudmanagerpd2.lua:1758
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:848
update() lib/setups/gamesetup.lua:696
update() lib/setups/networkgamesetup.lua:21
orig__update() core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by ATTAFWRD** [comment]
If Heist Intro disabled, it's fine.

**Comment by Xeletron** [comment]
Dev version right? I forgot to rename something, its fixed now

**Comment by ATTAFWRD** [comment]
Fixed!
