### ISSUE TITLE
[CTD] CAR SHOP inevitable assault after ECM ran out (DEV)

### ISSUE THREAD

**Issue by ATTAFWRD** [Pd2VoidTeam/VoidUI#38]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                @mods/Void                                          
UI/lua/HudAssaultCorner.lua:1503  end_update()                                        
      lib/setups/setup.lua:893  end_update()                                        
  lib/setups/gamesetup.lua:769  end_update()                                        
lib/setups/networkgamesetup.lua:33                                                      
core/lib/setups/coresetup.lua:583

**Comment by Fanged-Hex** [comment]
Thanks for reporting, we will look into it :)
