### ISSUE TITLE
Incorrect skip blackscreen intro times

### ISSUE THREAD

**Issue by VxWolf** [Pd2VoidTeam/VoidUI#40]
Releasing enter before the blackscreen intro is skipped when you have a custom time set for skipping it causes holding enter again to skip the intro use the vanilla time.

**Steps to reproduce:**

- Set the time to skip heist intro to a unique value > 0
- Hold enter to begin skipping it
- Release enter before it is skipped
- Hold enter again

**Comment by ATTAFWRD** [comment]
Maybe this ain't related but happened to me twice.
![20180328045135_2](https://user-images.githubusercontent.com/21013500/37997042-f0aee70a-3243-11e8-8903-3f8dcc488636.jpg)

**Comment by Xeletron** [comment]
Fixed both of these
