### ISSUE TITLE
Help, crash

### ISSUE THREAD

**Issue by EHOTIK911** [Pd2VoidTeam/VoidUI#50]
Application has crashed: C++ exception
mods/VoidUI-master/lua/HudHeistTimer.lua:253: attempt to perform arithmetic on field '_scale' (a nil value)

SCRIPT STACK

feed_heist_time() lib/managers/hudmanagerpd2.lua:1326
original() lib/managers/gameplaycentralmanager.lua:202
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/gamesetup.lua:712
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

**Comment by fangedhex** [comment]
I'm closing this issue cause there is no update about this bug now. It is maybe fixed.
