### ISSUE TITLE
VoidUI not working on Linux?

### ISSUE THREAD

**Issue by sketch54** [Pd2VoidTeam/VoidUI#56]
I've tried running VoidUI on Linux, almost any other mod I've tried has worked on the Linux version of Payday 2. Other HUD mods I've previously used such as WolfHUD, VanillaHUD+, and PocoHUD have worked fine. However, not this one. When I go to the Installed Mods menu, VoidUI appears to show, however it is completely absent besides that. I've tried removing every mod except VoidUI, however still not luck. I'd really like to try this mod out for myself. Any suggestions to get this working?

**Comment by dribbleondo** [comment]
That's quite surprising. I'll have to test it later.

**Comment by sketch54** [comment]
I'm running Linux Mint 20, with the newest installation of Steam and Linux-compiled SuperBLT if it's of any help to you.

**Comment by dribbleondo** [comment]
Duly noted. I'll see what I can find.

**Comment by steam-test1** [comment]
It's probably SystemFS:list the fix should be included in the next update

**Comment by sketch54** [comment]
Thanks, when will the next update be included? I'm eager to try out this HUD.

**Comment by steam-test1** [comment]
In the meantime, you can change line 79 in Main.lua from
`for _, file in pairs(SystemFS:list(VoidUI.mod_path.. "guis/textures/VoidUI")) do`
to
`for _, file in pairs(file.GetFiles(VoidUI.mod_path.. "guis/textures/VoidUI")) do`
The update should be released soon

**Comment by sketch54** [comment]
Thank you, however I'm still having issues. VoidUI appears to have loaded, but everything in the Mod Options menu has disappeared except for VoidUI. My settings for other mods are still retained and the Mod Keybinds is untouched. When I tried to click on VoidUI options, the menu was blank and my game crashed a few seconds after. Finally, I attempted to load into a heist and my game crashed before it fully finished loading.

**Comment by steam-test1** [comment]
Could you upload your mods/logs file that should show the error

**Comment by sketch54** [comment]
From mods/logs/crash.txt

```
Segmentation fault!

Obtained 26 C++ stack frames:
 0x7f71e06c0024 libsuperblt_loader.so : blt::error::handler(int)+0x294
 0x7f71dfd16210 libc.so.6 : +0x46210
                payday2_release() [0xa487a9]
                payday2_release() [0xa33678]
                payday2_release() [0xa3228e]
                payday2_release() [0xa32073]
                payday2_release() [0x6a68ee]
                payday2_release() [0x6966cb]
                payday2_release() [0x697f1d]
                payday2_release() [0x6adc89]
                payday2_release() [0xa36d45]
                payday2_release() [0x860a1e]
                payday2_release() [0x4c5a18]
                payday2_release() [0x4c5c38]
                payday2_release() [0x69f63b]
                payday2_release() [0x69f12b]
                payday2_release() [0x6a31f1]
                payday2_release() [0x6a3016]
                payday2_release() [0x6a2da8]
                payday2_release() [0x6a01a1]
                payday2_release() [0x444229]
                payday2_release() [0xe84269]
                payday2_release() [0xe9b0f6]
 0x7f71dfecb609 libpthread.so.0 : +0x9609
 0x7f71dfdf2293 libc.so.6 : clone+0x43

```

**Comment by steam-test1** [comment]
I meant the one which has the date _log.txt

**Comment by sketch54** [comment]
Going through the file, I found this 27 times.
```
FATAL ERROR:  (/home/dribbleondo/Documents/payday2-superblt/src/InitiateState.cpp:320) mods/Void UI/Main.lua:79: attempt to call method 'list' (a nil value)
stack traceback:
	mods/Void UI/Main.lua:79: in function 'LoadTextures'
	mods/Void UI/Main.lua:236: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:158: in function 'RunHookFile'
	mods/base/base.lua:150: in function 'RunHookTable'
	mods/base/base.lua:178: in function 'OrigRequire'
	mods/BeardLib/Core.lua:363: in function 'require'
	[string "lib/managers/hudmanagerpd2.lua"]:7: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:177: in function 'OrigRequire'
	mods/BeardLib/Core.lua:363: in function 'require'
	...
	mods/BeardLib/Core.lua:363: in function 'require'
	[string "lib/setups/networkgamesetup.lua"]:1: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:177: in function 'OrigRequire'
	mods/BeardLib/Core.lua:363: in function 'require'
	[string "lib/entry.lua"]:6: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:177: in function 'OrigRequire'
	mods/BeardLib/Core.lua:363: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk
```
The only difference between them being the timestamp which was at the beginning of the error and at `[string "lib/managers/hudmanagerpd2.lua"]:7: in main chunk`, the number 7 would be one higher for every mention of this.

After removing every mod except for VoidUI (only the mods folder, not mod_overrides, however I don't think I have anything that would interfere in that folder), I got [this](https://github.com/Pd2VoidTeam/VoidUI/files/7740003/2021_12_18_log.txt). It appears to allow me to load into a heist now, but the Mod Options menu still gives me the same result, specifically when I press Escape, while there is no other way to exit the menu.

**Comment by steam-test1** [comment]
Thanks there was two SystemFS:lists change line 265 of Main.lua to
`local menus = file.GetFiles(VoidUI.mod_path.. "menu/")`
The menu should load properly and no longer crash

**Comment by sketch54** [comment]
Thank you! Everything is working perfectly now. I'm glad I was able to try out this HUD and I will be keeping enabled.
