### ISSUE TITLE
Chat window is broken

### ISSUE THREAD

**Issue by Vitaliuz** [Pd2VoidTeam/VoidUI#69]
In the latest version _(v1.2.9.13)_ the chat windows got broken - the chat won't hide after a timeout.

Tried separating the mod from all the other mods _(disabling all the ones besides that one)_ and resetting its options to default _(VoidUI.txt)_ - all to no avail. Main files are bit-exact to the ones from the github, of course.

When you disable this mod - the chat disappears properly after a timeout.

**Comment by steam-test1** [comment]
Fixed in the latest update
