### ISSUE TITLE
Captain Winters police badge still appears even when the badge is disabled

### ISSUE THREAD

**Issue by VxWolf** [Pd2VoidTeam/VoidUI#7]

**Comment by FangedHex** [comment]
I looked into it but didn't find why this happen, I think @Xeletron can fix it :)

**Comment by Xeletron** [comment]
Its not a bug :P the police badge means he is giving the buff, the normal hud has that as well. even if the badge is disabled that should be visible

**Comment by VxWolf** [comment]
Is it meant to completely obscure the hostage counter and cover half of the assault ticker though?

**Comment by Xeletron** [comment]
Maybe 😄  Maybe Not 😠
