### ISSUE TITLE
We are aware about the linux not working

### ISSUE THREAD

**Issue by Fanged-Hex** [Pd2VoidTeam/VoidUI#9]
We can't support Linux for the moment because there is no SystemFS API inside blt4l
We are awaiting for blt4l to implement it and then I can work to fix the last bugs under Linux and we are good to go !

- Source : https://github.com/blt4linux/blt4l/issues/96

EDIT : The DB:create_entry is Overkill fault, they forget to implement into the linux binary because they are dumb developers ...

**Comment by ZNixian** [comment]
Can you change to using `file.GetDirectories` and `file.GetFiles` (see the [BLT4L docs](http://payday-2-blt-docs.readthedocs.io/en/latest/globals/file/)), as they both work across both platforms currently.

Alternatively, do you know what the return values for `SystemFS:list` are, and any gotchas that might be useful to know while implementing - I could probably add support for this in today, however I don't have a working windows copy of PAYDAY 2.

**Comment by ZNixian** [comment]
Also, it's worth noting that one of the APIs that the GNU+Linux version of PAYDAY 2 doesn't have is `DB:create_entry`. Roman Hargrave and I have both made considerable efforts to reverse-engineer PAYDAY 2 in this regard, but so far nothing has come out of it.

**Comment by Fanged-Hex** [comment]
I just missread it. I'm reading all the issues about that to get a good idea of the problem

**Comment by ZNixian** [comment]
See blt4linux/blt4l#100

**Comment by Fanged-Hex** [comment]
Seems to work now, if anyone can validate that VoidUI works under Linux now ?

**Comment by dribbleondo** [comment]
I can confirm that VoidUI runs under Linux with no trouble.
